pgood_wait: fix bool include
We don't actually have a CI build type for plain Make anymore, so we
don't get any repository level CI done for this repository.  The
Yocto recipe update failed with the following:

```
15:12:53 | pgood_wait.c:95:16: error: 'true' undeclared (first use in this function)
```

Make a simple fix to add `stdbool.h` in hopes that this solves it.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I64dd3cba36c7b9b3aa8111ffe6f7fb33088eb080